### ISSUE TITLE
切换服务器时出现oops对话框

### ISSUE THREAD

**Issue by BloodDragooner2** [moeyy01/mikuinvidious#1]
嗨你好！在MikuInvidious中选择新实例时，会出现一个糟糕的对话框！通过 Libredirect 扩展找到了这个项目。祝你的项目好运！
![picture](https://github.com/moeyy01/mikuinvidious/assets/117775945/d14d4247-3b85-4d17-b1f8-c6b942069363)

**Comment by moeyy01** [comment]
原作者正在重构，会推出新版本。目前版本很多功能因为某些原因已经无法使用
