### ISSUE TITLE
「space」页面不起作用？

### ISSUE THREAD

**Issue by NintendoManiac64** [moeyy01/mikuinvidious#2]
[英文 ▶ 中文翻译]
「space」页面不起作用？

https://space.bilibili.com/12434430

[https:///moeyy.cn/mikuinvidious/space/12434430](https:///moeyy.cn/mikuinvidious/space/12434430)

>Internal Server Error

>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

https://github.com/moeyy01/mikuinvidious/assets/11896003/49844763-4716-4f50-ab9b-b0507f03d55b

**Comment by moeyy01** [comment]
#3
